revert tests

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -106,32 +106,33 @@ jobs:
       - name: Run Tests
         run: dotnet test --no-restore --filter TextToSpeech.${{ matrix.test_type }}Tests
 
-      - name: Show logs api (if Selenium tests failed)
+      - name: Show logs (if Selenium tests failed)
         if: matrix.test_type == 'Selenium' && failure()
         run: |
           docker logs api || true
-
-      - name: Show inspect api (if Selenium tests failed)
-        if: matrix.test_type == 'Selenium' && failure()
-        run: |
-          docker inspect api || true     
-
-      - name: Show logs web (if Selenium tests failed)
-        if: matrix.test_type == 'Selenium' && failure()
-        run: |
           docker logs web || true
 
-      - name: Show logs db (if Selenium tests failed)
-        if: matrix.test_type == 'Selenium' && failure()
-        run: |
-          docker logs db || true
+      # - name: Show inspect api (if Selenium tests failed)
+      #   if: matrix.test_type == 'Selenium' && failure()
+      #   run: |
+      #     docker inspect api || true     
 
-      - name: Show docker inspect db (if Selenium tests failed)
-        if: matrix.test_type == 'Selenium' && failure()
-        run: |
-          docker inspect db
+      # - name: Show logs web (if Selenium tests failed)
+      #   if: matrix.test_type == 'Selenium' && failure()
+      #   run: |
+      #     docker logs web || true
 
-      - name: Show docker inspect elk (if Selenium tests failed)
-        if: matrix.test_type == 'Selenium' && failure()
-        run: |
-          docker network inspect elk 
+      # - name: Show logs db (if Selenium tests failed)
+      #   if: matrix.test_type == 'Selenium' && failure()
+      #   run: |
+      #     docker logs db || true
+
+      # - name: Show docker inspect db (if Selenium tests failed)
+      #   if: matrix.test_type == 'Selenium' && failure()
+      #   run: |
+      #     docker inspect db
+
+      # - name: Show docker inspect elk (if Selenium tests failed)
+      #   if: matrix.test_type == 'Selenium' && failure()
+      #   run: |
+      #     docker network inspect elk 
